export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_PLAY_INDEX = 'SET_CURRENT_PLAY_INDEX'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAY_LIST_VISIBLE = 'SET_PLAY_LIST_VISIBLE'

export const SET_MAX_WINDOW_STATE = 'SET_MAX_WINDOW_STATE'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_LOGIN_DIALOG_VISIBLE = 'SET_LOGIN_DIALOG_VISIBLE'

export const SET_USER_SONG_LIST = 'SET_USER_SONG_LIST'

export const SET_USER_LIKE_LIST = 'SET_USER_LIKE_LIST'